name: 'Socialism'
description: 'Update your social network feed based on git commit messages'
inputs:
  prefix:  
    description: 'Commit body prefix that will trigger the feed'
    required: true
    default: 'post:'
outputs:
  updates: 
    description: 'The networks that have been updated'
runs:
  using: 'node16'
  main: 'dist/index.js'
